In [2]:
import seaborn as sns
import numpy as np
import math
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import datasets

In [ ]:
global boston
global data
global target

In [ ]:
boston = datasets.load_boston()
data = pd.DataFrame(data=boston.data,columns=boston.feature_names)
target = pd.DataFrame(data=boston.target,columns=['MENV'])

In [ ]:
def reset():
    global boston
    global data
    global target
    boston = datasets.load_boston()
    data = pd.DataFrame(data=boston.data,columns=boston.feature_names)
    target = pd.DataFrame(data=boston.target,columns=['MENV'])

In [ ]:
data.head()

In [ ]:
target.head()

In [ ]:
def setting_data(data=None,features=None,target=None):
    data.insert(loc=0, column='constants', value=1)
    feature_matrix = data
    features = ['constants'] + features.tolist()
#     print('inside setting')
#     print(features)
#     print('out')
    return feature_matrix, features

In [ ]:
def predict_values(feature_matrix=None, weights=None):
#     print(type(feature_matrix))
    return np.dot(a=feature_matrix,b=weights)

In [ ]:
def gradient_descent(data=None, features=None ,target=None):
    feature_matrix, features = setting_data(data=data, features=features, target=target)
    weights = np.array([0]*len(features))

    predicted = predict_values(feature_matrix=feature_matrix, weights=weights)
    print(predicted)
    errors = np.subtract(predicted, np.array(target['MENV']) )
    print(errors)
    
    print()
    print(weights)
    print(weights.shape)
    print(type(weights))
    print()
    #print(features)
    print(type(features))
    print()
    #print(feature_matrix)
    print(feature_matrix.shape)
    print(type(feature_matrix))

In [ ]:
reset()
#gradient_descent(data=data, features=boston.feature_names, target=target)

In [ ]:
features = boston.feature_names.tolist()
features

In [ ]:
def feature_derivative(feature=None, errors=None):
    return 2*np.dot(feature,errors)

In [ ]:
def gd(data=None, features=None ,target=None,tolerance_gradient=0.01, tolerance_cost=0.0000001, step_size = 0.001):
    
    feature_matrix, features = setting_data(data=data, features=features, target=target)
    weights = np.array([0]*len(features))
    partials = np.array([0]*len(features))
    
    converged = False
#     print(feature_matrix)
#     print(feature_matrix.shape)
#     print(type(feature_matrix))
#     print('HERE')
#     print(feature_matrix[features[0]])
    x = 1
    iter_count = 0
    while not converged:
        
        predicted = predict_values(feature_matrix=feature_matrix, weights=weights)
#         print(predicted)
#         print(predicted.shape)
    
        errors = np.subtract(predicted, np.array(target['MENV']) )
        
        gradient_sum_squares = 0
        #Updating weights
#         print(feature_matrix[features[x]])
#         print(errors)
#         print('in loop')

        # task: can you get all the gradients and weights updates in one line
        for i in range(len(weights)):
            
            partials[i] = feature_derivative(feature_matrix[features[i]],errors)
            weights[i] -= step_size*partials[i]
#             print('partial[{}]: {}'.format(i,partials[i]))
            gradient_sum_squares += partials[i]
#         print('out loop',x)
        x+=1
        print(gradient_sum_squares)
        gradient_magnitude = np.sqrt(gradient_sum_squares)
        #input()
        
        if gradient_magnitude <= tolerance_gradient:
            converged = True
        iter_count += 1

        if iter_count > 5000:
            converged = True
        
    print(weights)
    return(weights)
        
#     print()
#     print(weights)
#     print(weights.shape)
#     print(type(weights))
#     print()
#     print(features)
#     print(type(features))
#     print()


In [ ]:
reset()
gd(data=data, features=boston.feature_names, target=target,step_size=0.000000000007,tolerance_gradient=25000000)

In [3]:
x = np.array([[1,1,1],[2,2,2],[3,3,3]])
x

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [35]:
y = np.array([1,2,3]).reshape((len(y),1))
y

array([[1],
       [2],
       [3]])

In [36]:

y.shape

(3, 1)

In [37]:
np.dot(x,y)

array([[ 6],
       [12],
       [18]])

In [6]:
z = np.array([[1,2,3],[1,2,3],[1,2,3]])
z

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [7]:
# If both a and b are 2-D arrays, it is matrix multiplication, but using matmul or a @ b is preferred.
np.dot(x,z)

array([[ 3,  6,  9],
       [ 6, 12, 18],
       [ 9, 18, 27]])

In [8]:
np.matmul(x,z)

array([[ 3,  6,  9],
       [ 6, 12, 18],
       [ 9, 18, 27]])

In [9]:
a = 5
a

5

In [10]:
# If either a or b is 0-D (scalar), it is equivalent to multiply and using numpy.multiply(a, b) or a * b is preferred.
np.dot(x,a)

array([[ 5,  5,  5],
       [10, 10, 10],
       [15, 15, 15]])

In [11]:
np.dot(a,x)

array([[ 5,  5,  5],
       [10, 10, 10],
       [15, 15, 15]])

In [44]:
# If both a and b are 1-D arrays, it is inner product of vectors (without complex conjugation).
a  =np.array([1,2,3]).reshape(-1,1)
np.dot(y,a)

ValueError: shapes (3,1) and (3,1) not aligned: 1 (dim 1) != 3 (dim 0)

In [42]:
y.T.shape

(1, 3)

In [14]:
x1 = np.arange(9.0).reshape((3, 3))
print(x1)
x2 = np.arange(3.0)
print(x2)
np.subtract(x1, x2)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
[0. 1. 2.]


array([[0., 0., 0.],
       [3., 3., 3.],
       [6., 6., 6.]])

In [18]:
a =5
np.multiply(a,y)

array([ 5, 10, 15])

In [19]:
y

array([1, 2, 3])

In [20]:
np.subtract(y,y)

array([0, 0, 0])

In [33]:
import sys
prev_cost = sys.maxsize

In [34]:
prev_cost

9223372036854775807